version: "3.9"
services:
    app:
        build: .
        image: iniquitybbs/iniquity:latest
        ports:
            - "22:22"
            - "23:23"
            - "24:24"
        volumes:
            - ./packages:/iniquity
            - ./data:/sbbs/data
