version: "3.9"
services:
    app:
        build: .
        image: iniquitybbs/iniquity:latest
        ports:
            - "22:22"
            - "23:23"
            - "80:80"
            - "443:443"
            - "1123:1123"
            - "11235:11235"
        volumes:
            - ./packages:/iniquity
            - ./data:/sbbs/data
