FROM node:18-bullseye-slim

WORKDIR /iniquity
COPY . .

# Install dependencies and build
RUN npm install && npm run build

# Expose ports
EXPOSE 23 80 443 1123 11235

# Start Iniquity BBS
CMD ["npm", "start"]
