version: "3.9"
services:
    runtime:
        build: .
        ports:
            - "22:22"
            - "23:23"
            - "80:80"
            - "443:443"
            - "1123:1123"
            - "11235:11235"
        volumes:
            - ./iniquity:/iniquity
            - ./data:/sbbs/data
