version: "3.9"
services:
    app:
        extends:
            file: ../../docker-compose.yml
            service: app
        image: iniquitybbs/archive:latest
        volumes:
            - ./dist:/iniquity
            - ./data:/sbbs/data
