version: "3.9"
services:
    app:
        extends:
            file: ../../docker-compose.yml
            service: app
        image: iniquitybbs/core:latest
        volumes:
            - ./dist:/iniquity
            - ./data:/sbbs/data
        entrypoint: node /iniquity/core/dist/index.js
        command: "core --help"
