version: "3.9"
services:
    runtime:
        extends:
            file: ../../docker-compose.yml
            service: runtime
        image: iniquitybbs/core:latest
        volumes:
            - ./dist:/iniquity
            - ./data:/sbbs/data
        entrypoint: node /iniquity/core/dist/commands/iniquity.js
        command: "iniquity --help"
