version: "3.9"
services:
    app:
        extends:
            file: ../../docker-compose.yml
            service: app
        image: iniquitybbs/core:latest
        volumes:
            - ./dist:/iniquity
            - ./data:/sbbs/data
        entrypoint: node /iniquity/cli/dist/commands/cli.js
        command: "cli --help"
