name: Release
on:
    push:
        branches:
            - master
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Release
              run: |
                  npm i -g npm@7
                  npm i -g lerna
                  lerna bootstrap
                  lerna exec --concurrency 1 -- npx --no-install semantic-release -e semantic-release-monorepo
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
